### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by 0vermind** [WildGums/Orc.CrashReporting#2]
Hi, great works!
The library seems very helpful but i don't understand how to use it. Is there any docs?
I only managed to add the lib to the project  using the lines in home and nothing more.

**Comment by GeertvanHorrik** [comment]
Nothing is required, it all works out of the box. See the example app for more info.

**Comment by 0vermind** [comment]
Sorry, but in the example app the send  by MailProvider is not used at all. How can I use it?

**Comment by GeertvanHorrik** [comment]
It should work out of the box if you install that package.
