### ISSUE TITLE
Can't find nuget packages xaml and email provider

### ISSUE THREAD

**Issue by vseledtsov** [WildGums/Orc.CrashReporting#3]
Can't find nuget packages  Orc.CrashReporting.Xaml and Orc.CrashReporting.Providers.Email
Example also doesn't work properly.
I have serialization exception 
![image](https://cloud.githubusercontent.com/assets/15861846/14853830/c17e7886-0c95-11e6-828c-e6cca08a2599.png)

**Comment by GeertvanHorrik** [comment]
1. You might have to check the "include prerelease" checkbox in visual studio
2. Could it be a first chance exception?

**Comment by vseledtsov** [comment]
1. Checked
2. Nope, build more than 2 times. Same exception.

**Comment by GeertvanHorrik** [comment]
1. I see now, sorry for the inconvenience. We will fix immediately.

**Comment by GeertvanHorrik** [comment]
Packages should be available on NuGet soon: https://www.nuget.org/packages?q=orc.crashreporting

**Comment by GeertvanHorrik** [comment]
2 is also fixed, releasing a new version now with the fix.

**Comment by vseledtsov** [comment]
Thank you!  You did a great job! You make WPF developer life easy :)

**Comment by GeertvanHorrik** [comment]
Thanks :) Let us know if you find more issues, and make sure to check out our other components, they're great as well (at least, we'd like to think so).

**Comment by vseledtsov** [comment]
I used almost all of them :+1:

**Comment by vseledtsov** [comment]
Add Dependencies to packages:

LoadAssembliesOnStartup.Fody

**Comment by GeertvanHorrik** [comment]
I understand, but don't want to force the users to do so.
